name: Run Demo Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: # allows manual runs

jobs:
  run-demo:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: godot-4.5

      - name: Unzip Godot build
        shell: bash
        run: |
          cd tools
          unzip godot.windows.template_release.x86_64.zip
          unzip godot.windows.editor.x86_64.zip

      - name: Install SwiftShader (CPU-based Vulkan implementation)
        shell: bash
        env:
          SWIFTSHADER_URL: https://github.com/jakoch/rasterizers/releases/download/20250311/swiftshader-win64-5.0.0.1.zip
        run: |
          curl -L -o swiftshader.zip "${SWIFTSHADER_URL}"
          mkdir swiftshader
          unzip swiftshader.zip -d swiftshader
          rm swiftshader.zip
          echo "${GITHUB_WORKSPACE}/swiftshader" >> $GITHUB_PATH

      - name: Import project
        shell: bash
        run: ./tools/godot.windows.editor.x86_64.exe --headless --editor --import --path . || true

      - name: Run demo
        shell: bash
        run: ./tools/godot.windows.template_release.x86_64.exe --path . --automate || true
